# Generated by Django 3.1.5 on 2021-01-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio $'),
        ),
    ]
